paths:
  static: public
  uploads: public/images

collections_config:
  pages:
    path: src/content/pages
    glob:
      - '**/*.md'
    url: '/[full_slug]/'
    icon: laptop_mac
    _enabled_editors:
      - visual

collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Data
    collections:
      - data
