timezone: Pacific/Auckland

paths:
  static: public
  uploads: public/images

collections_config:
  pages:
    path: src/content/pages
    glob:
      - '**/*.md'
    url: '/[full_slug]/'
    icon: laptop_mac
    _enabled_editors:
      - visual
    add_options:
      - name: Add New Page
        schema: default
        icon: pages
    create:
      path: '[relative_base_path]/{filename|slugify|lowercase}.md'
    new_preview_url: /
    _inputs:
      title:
        type: text
        comment: Controls the metadata title for the page.

collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Data
    collections:
      - data

data_config:
  icons:
    path: data/icons.json
  colors:
    path: data/colors.json
  tags:
    path: data/tags.json

file_config:

_inputs:
  content_blocks:
    type: array
    options:
      structures: _structures.content_blocks
      empty_type: array
